# Пользователь
MAX_EMAIL_LENGTH = 254
MAX_NAME_LENGTH = 150

# Тег
MAX_TAG_NAME_LENGTH = 32
MAX_TAG_SLUG_LENGTH = 32

# Продукт
MAX_PRODUCT_NAME_LENGTH = 128
MAX_MEASUREMENT_UNIT_LENGTH = 64

# Рецепт
MAX_RECIPE_NAME_LENGTH = 256
MIN_AMOUNT = 1
MIN_COOKING_TIME = 1
