# Generated by Django 5.1.1 on 2026-07-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('cooking_time__gte', 1)), name='recipe_cooking_time_gte_min'),
        ),
        migrations.AddConstraint(
            model_name='recipeproduct',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='recipe_product_amount_gte_min'),
        ),
    ]
