# Generated by Django 5.1.1 on 2026-07-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='recipe_cooking_time_gte_min',
        ),
        migrations.RemoveConstraint(
            model_name='recipeproduct',
            name='recipe_product_amount_gte_min',
        ),
    ]
